FROM wordpress:php8.2-apache

COPY custom.ini /usr/local/etc/php/conf.d/custom.ini

LABEL project="Dandelion"
LABEL service="custom-wordpress"
LABEL base_image="wordpress:php8.2-apache"
LABEL description="Custom WordPress image for Ansible-based cloud infrastructure automation project"
